### ISSUE TITLE
The Websocket just receive data one time  and then closed somehow!

### ISSUE THREAD

**Issue by wenewzhang** [wjfree/mixin-csharp-sdk#1]
Hi,
  I try to make the websocket connection  always connected,  but the connection closed after  received data one time! Is the websocket of NETCore 2.0 support asynchronously? If not, maybe https://github.com/ninjasource/Ninja.WebSockets  is a better choice!

Regards

my code   https://github.com/wjfree/mixin-csharp-sdk/blob/master/mixin-sdk-test/unit_test.cs#L204             
as below.

mixinApi.SendListPendingMessage();
            do
            {
//  comment SendListPendingMessage in StartReceive
                mixinApi.StartRecive();
                //var msg = Console.ReadLine();
                //mixinApi.SendTextMessage("bfa147b5-1320-3c48-a758-0401050dbb3f", msg).Wait();
                System.Threading.Thread.Sleep(1000);
            } while (true);

**Comment by wjfree** [comment]
please folow this
```
            mixinApi.WebSocketConnect(HandleOnRecivedMessage).Wait();
            mixinApi.StartRecive();

            do
            {
                var msg = Console.ReadLine();
                mixinApi.SendTextMessage("fd72abcd-b080-3e0e-bfea-a0b1282b4bd0", msg).Wait();
                
            } while (true);

        }

        static void HandleOnRecivedMessage(object sender, EventArgs args, string message)
        {
            System.Console.WriteLine(message);
        }

```
HandleOnRecivedMessage method should be implemented.

**Comment by wjfree** [comment]
I'll try Ninja.WebSockets and compare with System.Net.WebSockets, thank you.

**Comment by wenewzhang** [comment]
Hope so.
